### ISSUE TITLE
Why is the Levenshtein similarity between empty strings 0?

### ISSUE THREAD

**Issue by jsh9** [life4/textdistance#63]
Code to reproduce:
```python
import textdistance
ans1 = textdistance.levenshtein.normalized_similarity("", "")
ans2 = textdistance.levenshtein.similarity("", "")
```
Both `ans1` and `ans2` are 0.  But they should be both 1, right?  Two empty strings should be considered identical.

**Comment by orsinium** [comment]
+ `levenshtein.similarity` from empty strings is 0, that's the correct result. 0 symbols are similar :)
+ `levenshtein.normalized_similarity` should be 1, I guess, yes. Now it's 0 because it's quite an open question what should be a result of `0/0`. Mathematically speaking, `x = 0/0 -> x*0 = 0 -> x is anything`. On practice, let's fix it to 1.
